version: "3.4"
networks:
  proxynetwork:
    external: true
  net:
    driver: overlay
    attachable: true
services:
  apache:
    image: httpd
    depends_on:
      - phpfpm
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.www-laravel.rule=Host(`laravel.lxc`, `www.laravel.lxc`)"
        - "traefik.http.middlewares.laravelredirectregex.redirectregex.regex=^http://laravel.lxc/(.*)"
        - "traefik.http.middlewares.laravelredirectregex.redirectregex.replacement=http://www.laravel.lxc/$${1}"
        - "traefik.http.routers.www-laravel.entrypoints=web"
        - "traefik.http.services.www-laravel.loadbalancer.server.port=80"
  phpfpm:
    image: koromerzhin/phpfpm:7.4.12-xdebug
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
