version: "3.4"
networks:
  proxynetwork:
    external: true
  net:
    driver: overlay
    attachable: true
services:
  apache:
    image: httpd
    depends_on:
      - phpfpm
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.laravel.rule=Host(`laravel.traefik.me`)"
        - "traefik.http.routers.laravel-tls.tls.domains[0].main=laravel.traefik.me"
        - "traefik.http.routers.laravel-tls.tls.domains[0].sans=laravel-*.traefik.me"
        - "traefik.http.services.laravel.loadbalancer.server.port=80"
  phpfpm:
    image: koromerzhin/phpfpm:7.4.12-xdebug
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
    deploy:
      labels:
        - "traefik.enable=false"
