version: "3.4"
networks:
  proxylampy:
    external: true
  serverlampy:
    external: true
volumes:
  mariadb_data:
services:
  apache:
    networks:
      - net
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.laravel.rule=Host(`laravel.traefik.me`)"
        - "traefik.http.routers.laravel-tls.tls.domains[0].main=laravel.traefik.me"
        - "traefik.http.routers.laravel.tls=true"
        - "traefik.http.services.laravel.loadbalancer.server.port=80"
  phpfpm:
    networks:
      - net
      - serverlampy
