version: "3.4"
networks:
  proxyhackariens:
    external: true
  serverhackariens:
    external: true
  net:
    driver: overlay
    attachable: true
services:
  www:
    image: koromerzhin/php:8.4.3-apache
    depends_on:
      - mariadb
      - mercure
      - mailhog
      - redis
    volumes:
      - ${PWD}/apps:/var/www/:rw
      - ${PWD}/conf/php.ini-production:/usr/local/etc/php/conf.d/php.ini
      - ${PWD}/conf/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ${PWD}/conf/apache2/apache2.conf:/etc/apache2/apache2.conf:ro
      - ${PWD}/conf/init-laravel.sh:/usr/local/bin/init-laravel.sh:rw
    command: >
      sh -c "
        chmod +x /usr/local/bin/init-laravel.sh &&
        /usr/local/bin/init-laravel.sh &&
        apache2-foreground
      "
    networks:
      - net
      - serverhackariens
      - proxyhackariens
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.laravel.rule=Host(`laravel.hackariens.fr`)"
        - "traefik.http.routers.laravel.tls=true"
        - "traefik.http.routers.laravel.tls.certresolver=myresolver"
        - "traefik.http.services.laravel.loadbalancer.server.port=80"